name: Build and Release APK
on: push
jobs:
  hosting:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v1

      # Install Flutter command
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.5'
          channel: 'stable'

      # Build Website
      - name: Build Website
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
        working-directory: ./